:icons: font
:authors: Tomasz Borek, Paweł Kierat, Marcin Ogorzałek
:copyright: Copyrighted by EPAM Systems
= War card game

Your job is to deliver a working program per these requirements. Minimum allowed version of Java: 11. Anything higher is allowed. All games need to support special scenario codes.

[IMPORTANT]
.Screen templates
====
For your convenience, screen templates are in separate files and are included here. Heck! We even made a backup copy, so if you (accidentally or not) change something in the screens, `backup.screens` got you covered.

CAUTION: Be aware, GitHub doesn't know how to treat such includes properly so reading the `adoc` version of this file in a browser isn't the best idea (you will see link:filename.screen). We recommend reading the HTML version OR opening this in IDE with Asciidoctor support (Intellij with a plugin for instance).

[CAUTION]
.Don't install the Aurora framework plug-in in IDE for the `.screen` files. 
In case you will open the `.screen` files in the IDE, Intellij suggests using a plugin - DON'T. The plugin is for Aurora framework. I certainly didn't had it in mind when crafting the screen files and I know NOT what will happen should you install the plug-in. :-) Again: this just means you should not install the plug-in!
====

== Rules

. 2-5 computer players (no interaction with a human required, aside from starting the program),
. number of players is given as a starting parameter,
. console program - the game prints to console,
. decks: large (52 cards, no jokers) or small (24 cards, no jokers),
. decks are chosen per starting parameter,
. winner is the one with all cards,
. all players have only their names: player1, player2, ..., player5,
. aces are highest, 2s - lowest (9s for small deck),
. for grading purposes: all projects need to honour special scenario codes.
. regionalize the game - all outputs should come in two languages (English and one more, of your choice)
. game should log important information to a file using a modern logging library

IMPORTANT: **all screens MUST be as presented here, to the letter, to the dot, even with mistakes**. The game doesn't pause, the game doesn't break, the game doesn't prettify the output, the game doesn't page the output. Our scripts will do that so your game **MUSTN'T**. Seriously. We most likely will drop games which won't honour this. 0/10, don't recommend, no grading.

TIP: special scenario codes are triggered by input parameters and set the game as specified. They are incredibly useful for our tests.

== Starting the program

Program invocation should be like:

1. `java -jar target/War.jar 4 small`
2. `java -jar target/War.jar 4 large`

where first parameter can have inputs between 1-5 and second: only "large" or "small" (the case should not matter).

Bad inputs should be corrected: so `0` becomes `1`, `-5` becomes `1`, `1231241431` becomes `5` and `6` becomes `5`. Similarly, `LaRgE` becomes `large` and `SMaLL` becomes `small`.

TIP: JAR plugin configuration is given along with basic files in starting repository. If you won't botch it, it will run. Does it fulfill all requirements though?

=== Usage

First-timers don't know how to run a program. Old-timers may forget how to run it. Which params to give. In what order. Therefore it's an established tradition that running a program BADLY should prompt the program into printing the correct usage - or usage for short.

----
include::0_usage.screen[]
----

Make sure you have a `usage` function that takes care of that (bonus points if it's OO!).

=== What usage DOESN'T say - special scenario codes

For the sake of testing your game, it needs to honour special scenario codes. Which means:

. if there's a JSON file named `ssc_???.json` present in the same directory where the JAR is it needs to be picked up.
.. question marks in the name merely mean there may be something between `ssc_` and `.json`, of a variable length
. said file will have row per a player, so for 3 players it will look like that:

.ssc_example.json
----
include::ssc_example.json[]
----

With a file like that:

. game should start with a small deck and 3 players (there are 24 cards in the file)
. player1 should get a hand with 2 aces, 3 10s and 2 9s and a valet. 
. player2 should get 2 9s, 3 valets, a queen, a king and an ace
. player3 should get the remaining cards in the deck.
. game should begin WITHOUT dealing 
.. dealing is skipped if the special scenario code is present
.. instead a String "special scenario code: CAPITALIZED NAME" of the special scenario is displayed
.. for the file above that would be `EXAMPLE`
.. the name is the `???` part of the file name, so for `ssc_player1_winS_In_7_MoVeS.json` it should be `special scenario code: PLAYER1 WINS IN 7 MOVES`
. BONUS points for CHECKING that the file isn't corrupted
.. not enough cards for a deck
.. too many cards for a deck
.. too many players
.. these should cause a `SpecialCodeFileMangledException`
.. bad JSON syntax should cause a different exception
.. exceptions should have clear error messages, allowing to recover, hinting how to fix the file

[TIP]
.Why? How? What for?
====
We want you to do that to learn OO design and programming by practicing it. 

You should take into account that testing randomness is difficult and use the special scenario codes to test-drive your implementation of the game.

With this you can have a predictable game - give your players cards and the result should be clear, along with how each turn should look like.
====

== Game output

Game is a sequence of screens:

1. Dealing screen - shows up once,
2. Game screen - shows up multiple times and reflects changes in the game,
3. War screen - may be absent, may show up multiple times, if it does, it replaces the game screen for that turn,
4. End screen - shows up once.

IMPORTANT: every screen of the game is SEPARATED from another screen by a SEPARATOR: **precisely** 9 "=" characters followed by exactly **two** blank lines, so altogether 3 lines of text.

Thus your game will be outputting screens in the order above. 

=== Automated gameplay!

You probably realized that this program is non-interactive. This is a zero-player game: no HUMAN players are needed. User launches the game with two parameters and that's it. The rest is just program executing and printing.

This means:

1. no human interaction,
2. no waiting for humans,
3. no keyboard input,
4. no exception handling - _except_ input parameters of course.

=== Handling bad values in input params

We want you to catch bad values, correct them to default ones and inform the user like so:

. "Values were corrected to 2 players on a SMALL deck" - when both values were corrected,
. "Number of players corrected to X, you provided Y" - when the number is too small or too large,
. "Number of players set to 2, you provided unparseable input Y" - when something that couldn't be parsed to a number was given,
. "Deck set to SMALL, you provided unrecognized value: V" - when the user gave a value we could not recognize.

NOTE: we don't inform about lower- or upper-case corrections in deck type. Those are corrected silently.

== 1. Dealing

. Deck should be shuffled. Shuffling should be pseudorandom (some repetitions in the shuffled deck are fine, too many are not - we suggest to learn the `Random` class' API).
. Cards should be randomly distributed to all players.
. First player to get a card is player1, then 2 etc.
. It's possible that some players will get LESS cards than others! E.g. 52 cards, 5 players, all get 10 cards, 2 remaining cards will be distributed to player1 and player2.
. LUCKY PLAYERS are those who received extra card and are written in the order of dealing (player1 is always first).

=== Dealing screen

----
include::1_dealing.screen[]
----

1. Players' hands are printed in brackets: `[]`
2. They are sorted, descendingly.
3. Duplicated values are next to each other: 4, 4, 4...
4. Lucky players are those who received extra card and are written in the order of dealing (player1 is always first). There may be none: then the program should state `none` instead of listing them. Both a list and a `none` end with a dot.
5. SEPARATOR is as defined earlier.

== 2. Game screen

Once dealing is done, we move on to actual gameplay. The game prints the following screen to the console each turn:

----
include::2_game.screen[]
----

1. turn numbering starts at 1,
2. `a` is the number of players (in the example above - at least 3),
3. `b` is the deck: large or small,
4. `c` is current turn number,
5. `d` is the number for leading player - so between 1 and 5 -> playerd becomes player1 (or 2, or...),
6. `e` is the number of cards that the leader holds,
7. deck size is 52 or 24, depending on the deck size chosen,
8. SEPARATOR is as defined earlier.

CAUTION: in case of two (or more) players having the same number of cards, the message should be `DRAW with e/DECK_SIZE cards`.

=== Counting cards

Happens every turn AFTER cards change hands and dropped players disappear (more on that later).
Thus, the `e/DECK_SIZE` reflects the situation from the beginning of the turn.

NOTE: leader that is 'marked' so on the screen is just the person who currently holds the most cards and may not be the final winner!

=== Playing

. Each player (starting from player1) puts a card on the table.
. The highest card wins them all (colours matter not). Its owner collects all the cards on the table.
.. Order of collection starts with player with the lowest number.
. Next turn - and so on until only one player has cards - that's the winner.
. For screen here, see game screen above.
. The player who lost his cards simply disappears from the game screen. His line simply stops appearing. So if we had a 3 player game and player2 lost his last card, then in the next turn we would have a screen that shows: 

----
WAR, a-1 players, b deck, turn #c - playerd leads with e/DECK_SIZE cards
Player1 played: 14
Player3 played: 2
SEPARATOR
----

=== Changes between game screens

Each game turn updates the screen:

. turn number goes up,
. player who leads may change,
. number of players may change (as described above),
. param `e` should change reflecting how many cards the new leader has.

== War

If there are TWO OR MORE highest cards, we have a war. War is a series of clashes (at least two) that ends when one player wins the clash, uncontested. War takes an entire turn (so participants clash and clash and clash until one of them wins over everyone else and turn number is NOT increased.

[NOTE]
.War screen replaces the game screen?
====
Remember that from the game output section? This means you will print game screen only if there's no war. 
====

1. All cards that are lower than the fighting pair are stored aside. They are lost to their owners, they will be the prize of a winner.
2. War is *only* played among highest cards. So, if we have four eights and a nine, nine wins without a war. If we have four eights and a seven, four players wage war, and the player who played a seven loses a card to the winner.
3. Warring players put out next card from their queues HIDDEN (it's represented as a `?`).
4. Warring players put out next card revealed - these cards get compared, highest one wins.
5. Winner takes all the cards that participated in the war.
6. If a player runs out of cards during war - that player loses automatically.
7. If the cards put out in point #4 are equal - we play war again (between those who are equal) - unless there's a higher card (war is only played between highest cards, remember?).

=== War screen

----
include::3_war.screen[]
----

. `a`, `b`, `c`, `d`, `e` - stay as they were.
. The lines surrounding the WE HAVE A WAR header are equal in length, and the length is easy to check with JShell! Remember: precision matters!
. If war lasts more than one reveal, we continue adding columns with `?` and new cards until a winner is found.
. SEPARATOR is as defined earlier.
. Notice the card 11 - that's a valet (jack).

=== Counting cards DURING war

If there's no leader (`e` parameter same for more than 1 player) things should be same as for normal gameplay. Also, we don't change that value DURING the war (so it reflects the state of affairs when current war began). So, even if player5 won several clashes (rounds of war) and he now IS a leader (has most cards) it doesn't matter for now. It will matter, once the turn ends.

IMPORTANT: war or no war, we count cards as we did - when turn ends and AFTER cards change hands. Even it this means 'leader' is marked incorrectly.

=== What when one loses the game during war?

Player who lost, simply stops being updated, so if he put out 6 cards and lost them all, he doesn't output any more cards in subsequent rounds (clashes).

=== End of Cards event

EoC event happens when - during war - one cannot put out next hidden or revealed card. This automatically marks that player as a loser and all his cards are forfeit - they will belong to current war's winner.

A special case of this occurs when all warring players cannot put down a card AT THE SAME TIME:

----
WAR, 3 players, SMALL deck, turn #122 - DRAW with 8/24 cards
================================================================
                 WE HAVE A WAR LADIES AND GENTLEMEN!
================================================================
Player1 played: 9 ? 12 ? 10 ? 13 ? EoC
Player2 played: 9 ? 12 ? 10 ? 13 ? EoC
Player3 played: 9 ? 12 ? 10 ? 13 ? -----------> WINNER FOUND!

War lasted 4 rounds.
SEPARATOR
----

What happened?

. At turn 122 war happened when everybody had 8 cards (DRAW, no leader).
. No game screen happened, first war screen happened instead showing all players playing 9s.
. 2nd round of war, hidden cards were placed down and no winner was found, 2nd war screen was done, updated.
. 3rd round of war, hidden cards were placed down, still no winner, 3rd war screen was printed.
. 4th round of war (the screen you see above) hidden cards were placed down and *then everybody ran out of cards*.
. Player1 first! , this player lost the game, but others still have cards.
. Player2 was tallied next, this player lost the game, but one more player has cards.
. Player3 is the only player with cards, he's the winner.
. EoC markers were printed for players who had *lower* numbers.
. Remaining player is marked on screen as a winner *despite him, too, being out of cards*.
. Next screen is the *ending* screen!

CAUTION: for clarity's sake - if it wouldn't be a draw but there would be a leader with - say 12/24 cards - before this war happened, he would've won earlier, when his opponent's would've ran out of cards. War screens would look similar, but with less rounds and cards and earlier EoC / winner marks. Game would've still proceed to the ending screen.

=== Changes between war screens

Each war round updates the screen:

. round number goes up,
. number of players may change (as described above),
. new hidden cards appear with each clash (marked as `?`),
. new revealed cards appear with each clash.

Remember: war lasts ONE TURN, so game turn and leader and his card number (or "DRAW") stay the same. 

== Ending

No scoring. Simple message is enough: 

----
include::4_end.screen[]
----

WARNING: location of the SEPARATOR has moved! It's not CLOSING the screen but OPENING it. This means there'll be 2 SEPARATORs in a row.


== Handling files

Aside from special scenario codes you need to:

. log important information
. have the game regionalized - we suggest using `properties` for it but feel free to go your own way

=== Regionalization

. you will need to regionalize the `.screen` files
. English is the primary language, the default language
.. not having English counts as FAILING the task
. second language is up to you: Polish, French, Italian, Russian, Ukrainian
.. game should work in both!
. tests will be run in English (firstly and foremostly)

=== Logging

IMPORTANT: logging at most verbose level practically DUPLICATES the outputs from your UI plus offers debug / tracing info. Therefore - do it to a file, not to console.

. for auditing purposes game should allow log the entire game to a file
.. file should be called `audit_yyyy_mm_dd_HH_MM_ss.log` - which means year, month, etc.
. log levels should be customizable via a config file
. on FATAL (or equivalent - most serious) logging level the game should ONLY display critical messages
.. exceptions
.. crashes
.. final result
. on ERROR (or second most serious) logging level the game should display
.. everything from the higher level
.. wars (when two players put out a same card)
. most verbose level has everything, duplicating (or perhaps more) the output 
. again: all logging is done to a file

== Troubleshooting

This section offers technical (and other) help in case you're stuck with something.

[qanda]
How to build the jar file?:::
  `mvn package` from the main dir of this project, same place where this readme is located, *from the command line*.
I want to use Java 14! Can I?:::
  Sure. Bump the version in the `pom.xml`, switch your IDE settings (steps are IDE-dependent - look for yours), run with `java --enable-preview -jar target/War.jar number deckType` if you enabled preview features or without (the `--enable-preview`) if you didn't.
I accidentally crashed my screen files. How to restore them?:::
  A) use git to do that, and in case you can't B) go to `backup.screens` and overwrite your modified files with the ones there. We suggest *copying*, not *moving*, so you still have the backup.
How will my work be graded?:::
  If it doesn't work - it failed. Work == per requirements. We grade: working features, tests, Maven, Git, OOP, FP, threads, collections, advanced coding principles / techniques, error handling, generics... if it was taught during course we grade it. If it wasn't, and you introduced it, we grade it (but leniently). Code quality is graded at the end of: works, works well, is tested, is tested well, is documented, is documented well, is coded, is coded well.
How will you run my work?:::
  We will take your code from your repository via `git clone`. We will build it via `mvn package`. We will run it via appropriate `java -jar` command. We will look in your readme for details if something goes wrong with or during these steps. We will provide special scenario codes and see the results.
I want to use Graphical Interface! What now?:::
  Excellent! First deliver the version as specified here (we think that will be complex and challenging on its own). Then `git tag` it and move on to GUI. 

=== Assumptions, doubts, other remarks

. ask in the chat. There is an entire channel dedicated to Q&A.
. look in `remarks.md` file in the same directory
.. it's also an excellent place to leave some instructions for us, if your game requires any
